name: 'Build Release'
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  docker:
    name: Docker Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker
        uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
          build-args:
            EXTRA_BUILD_APK_PACKAGES=apk-tools
            REBAR_BUILD_TARGET=miner
            VERSION=${{github.ref_name}}
          tags:
            ghcr.io/${{ github.repository_owner }}/miner:miner-amd64-${{github.ref_name}}